on:
  release:
    types: [created, published]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.17.linux-amd64.tar.gz"
        binary_name: "v2ray-proxy"